name: test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    stragegy:
      os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    steps:
      - name: install zig
        uses: mlugg/setup-zig@v2
        with:
          version: master
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: zig build test
