name: test
on: [push]
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install zig
        uses: weskoerber/setup-zig@main
      - name: print zig version
        run: zig version
      - name: ls
        run: ls -lah
      - name: test
        run: zig build -Dexamples=true
