name: test
on: [push]
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: clone zvm
        run: git clone https://github.com/weskoerber/zvm
      - name: install zig
        run: ./zvm/zvm --verbose install --use master
      - name: print zig version
        run: zig version
      # - name: install zig
      #   uses: weskoerber/setup-zig@main
      # - name: test
      #   run: zig build -Dexamples=true
