name: test
on: [push]
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: install zig
        uses: weskoerber/setup-zig@main
      - name: test
        run: zig build -Dexamples=true
